apiVersion: apps/v1
kind: Deployment
metadata:
  name: new-repo-deployment
spec:
  replicas: 1  # Number of Nginx replicas you want
  selector:
    matchLabels:
      app: new-repo-deployment
  template:
    metadata:
      labels:
        app: new-repo-deployment
    spec:
      containers:
      - name: new-repo-deployment
        image: nginx:latest  # Use the Nginx Docker image
        ports:
        - containerPort: 80  # Port to expose
